### ISSUE TITLE
Grammatical error and awkward wording

### ISSUE THREAD

**Issue by Luis-Licea** [CourtBouillon/www-courtbouillon#41]
https://github.com/CourtBouillon/www-courtbouillon/blob/9b9dae0f9d28a04545936f878740a07a54dc7ea3/templates/pydyf.html.jinja2#L41

The sentence "by almost every computer users all around the world" is grammatically incorrect because "every" should be used with singular nouns, so it should be "by almost every computer user all around the world". The corrected sentence is still awkward. I think "by computer users all around the world" would be better.

**Comment by liZe** [comment]
Hi!

Thanks for reporting this issue.
